### ISSUE TITLE
HQP  can't find my Pi

### ISSUE THREAD

**Issue by Bobxyo** [lin-silas/pcp-naa#2]
看见别的库里面有中文，想必是同胞了啊
我在4B上先安装了嵌入版，声音确实不错，只是升频DSD有些算力不足，就想改成NAA，用虚拟机装个Linux版的HQP。先是在我的Mac上安装了HQP Desktop版，然后把装过嵌入版的4B安装了一遍NAA；在PCP的WebUI中，看见启动项目里面有NAA.sh，但是在桌面版里面看不见，是要重新刷一次系统吗？

**Comment by lin-silas** [comment]
剛剛修正了一些程式的 bug，麻煩您重裝一遍哦

另外 PCP8 中文的原作者提供了新的 kernel，值得一試

pCP8 (recommended)

https://github.com/sam0402/pcp-44.1KHz/raw/master/pCP8-Q176+44.img.7z.001

https://github.com/sam0402/pcp-44.1KHz/raw/master/pCP8-Q176+44.img.7z.002

It is recommanded to change these settings:

Choose [Squeezelite Settins] to choose your ouput setting and [Save].
Choose [Tweaks] -> [pCP Kernel Tweaks] -> [Kernel Frequency] -> [176]
Choose [Tweaks] -> [pCP Kernel Tweaks] -> [Advanced Overclock] -> [1960] (Optional, if your have good heat treatment.)

如果你的散熱做得不錯，可以考慮下面這個終極版本
https://github.com/sam0402/pcp-44.1KHz/raw/master/[pCP8-Q264x.img.7z.001
https://github.com/sam0402/pcp-44.1KHz/raw/master/[pCP8-Q264x.img.7z.002
Overclock 調成 2168

**Comment by Bobxyo** [comment]
哈哈哈，自己折腾好了又！
可能是服务没有启动成功，重启了几次后就好了，谢谢回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lin-silas/pcp-naa"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 上午10:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lin-silas/pcp-naa] HQP  can't find my Pi (Issue #2)





 
麻煩提供一下 HQP Desktop 的版本，我用 Mac 試試。
